### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by UweKeim** [Blazor-University/blazor-university-com#29]
On the page https://github.com/Blazor-University/blazor-university-com/blob/main/source/blazor-university-com/input/pages/components/literals-expressions-and-directives/directives/index.md there is a link named "Two way binding" that points to https://blazor-university.com/javascript-interop/calling-javascript-from-dotnet/passing-html-element-references but should point to https://blazor-university.com/components/two-way-binding/ in my opinion.

**Comment by StevenTCramer** [comment]
Ah thanks, you are correct. 

Fixed in #30  

FYI we made all the source documents public on GitHub to make it easy to do a PRs also.  You can click Edit on any page

![image](https://user-images.githubusercontent.com/357219/222325613-d4ec9845-b011-4bcf-ac17-575023a95e49.png)

Thanks.
